# Science Fact Creator Configuration
content_prompt: |
    Create an engaging and educational short video about a fascinating science fact.

    The video should focus on: {detail}
    
    Guidelines:
    - Final video should be around 50~65 seconds
    - Present the information in a clear and engaging way
    - Use simple language to explain complex concepts
    - Include interesting visual elements that help explain the concept
    - Make the content memorable and shareable
    - End with a thought-provoking question or call to action
    - Target audience 10~25 years old
    - Make a hook more interesting with a surprising statement or question about a key scene element.
    
    Target Audience: Science enthusiasts, curious learners, educators.
    Core Principle: Make complex ideas accessible and exciting.
    Tone: Vibrant, welcoming, balanced between rigor and warmth. Precise yet conversational language.
    Goal: Transform intimidating concepts into journeys of discovery.
    Structure: Multi-layered comprehension (fundamental, contextual, future).
    Engagement: Storytelling (analogies, digestible segments, critical thinking).
    Impact: Intellectual catalyst, active exploration.
    Ethics: Diverse perspectives, inclusive language, nurture curiosity.
    Success Metrics: Engagement, comprehension, inspiration to learn.
    Ultimate Aim: Transformative content, active participants in the narrative of knowledge
    
    Guidelines for captions:
    - Hook your audience with a surprising statement or question about a key scene element, like "What?! banana is radiation?" or "Human body can glow?!(NO emojis)"

    LIST OF IMAGE STYLES: {image_style_list}
    FORMAT YOUR RESPONSE USING THE FOLLOWING JSON STRUCTURE:

    {{
        "video_title": "Title of the video (Catchy and intriguing, emoji included)",
        "video_description": "Brief description of the video content, highlighting the fun and interesting aspects, emoji included.",
        "hashtags": ["hashtag1", "hashtag2", "hashtag3"],
        "hook": {{
            "script": "Narration text for the hook, designed to grab attention immediately.",
            "captions": ["caption1", "caption2"],
            "image_keywords": ["keyword1", "keyword2", "visually striking"],
            "scene_description": "Provide an extremely detailed visual description of the scene including: primary subjects/objects and their appearance, spatial arrangement, lighting, colors, atmosphere, camera perspective, background elements, textures, and any other important visual details that would allow an AI image generator to create a photorealistic and compelling image. Be specific about what's visible in the foreground, midground, and background. Aim for a visually stunning hook.",
            "image_to_video": "Description of how the static image should be animated or transformed into video, adding dynamism.",
            "image_style_name": "Style of the image, choose best style that fits the content from the 'LIST OF IMAGE STYLES' above."
        }},
        "scenes": [
            {{
                "script": "Narration text for scene 1, explaining the first key concept in a simple and engaging way.",
                "captions": ["caption1", "caption2", "caption3"],
                "image_keywords": ["keyword1", "keyword2", "illustrative"],
                "scene_description": "Detailed description of what should be shown in this scene, focusing on clear visuals that illustrate the scientific concept. Use clear visual metaphors and analogies.",
                "image_to_video": "Description of how the static image should be animated or transformed into video, enhancing understanding.",
                "image_style_name": "Style of the image, choose from the following: Scientific Illustration, Cosmic Watercolor, Futuristic Digital Render, Natural History Engraving, Minimalist Infographic, Molecular Abstract, Retro Scientific Poster, Bioluminescent Fantasy, Quantum Geometry, Ecological Collage"
            }},
            {{
                "script": "Narration text for scene 2",
                "captions": ["caption1", "caption2", "caption3"],
                "image_keywords": ["keyword1", "keyword2", "illustrative"],
                "scene_description": "Detailed description of what should be shown in this scene, focusing on clear visuals that illustrate the scientific concept. Use clear visual metaphors and analogies.",
                "image_to_video": "Description of how the static image should be animated or transformed into video, enhancing understanding.",
                "image_style_name": "Style of the image, choose from the following: Scientific Illustration, Cosmic Watercolor, Futuristic Digital Render, Natural History Engraving, Minimalist Infographic, Molecular Abstract, Retro Scientific Poster, Bioluminescent Fantasy, Quantum Geometry, Ecological Collage"
            }}
        ],
        "conclusion": {{
            "script": "Narration text for conclusion with a clear call to action, leaving the viewer with a sense of wonder.",
            "captions": ["caption1", "caption2"],
            "image_keywords": ["keyword1", "keyword2", "engaging"],
            "scene_description": "Detailed description of what should be shown in this scene, reinforcing the key takeaway and encouraging interaction.",
            "image_to_video": "Description of how the static image should be animated or transformed into video, ending on a memorable note.",
            "image_style_name": "Style of the image, choose from the following: Scientific Illustration, Cosmic Watercolor, Futuristic Digital Render, Natural History Engraving, Minimalist Infographic, Molecular Abstract, Retro Scientific Poster, Bioluminescent Fantasy, Quantum Geometry, Ecological Collage"
        }},
        "music_suggestion": "Suggestion for background music that fits the mood: upbeat, curious, and engaging."
    }}

    IMPORTANT SCENE CREATION GUIDELINES:
    - Create a natural flow of scenes, with each scene representing a distinct visual moment or story point.
    - Include an opening hook scene and a conclusion(call-to-action) scene.
    - Each scene should have a clear purpose in advancing the story or explaining the concept.
    - Hook scene should be 2~4 seconds, designed to be highly engaging.
    - Conclusion scene should be 2~5 seconds, designed to leave a lasting impression.
    - Other scenes should be 2~9 seconds, focusing on clear and concise explanations.
    - Number of scenes, including hook and conclusion, must be more than 9.

    SCENE DESCRIPTION GUIDELINES:
    - scene_description should include description about main subject, supporting elements, and background elements.
    - scene_description should include description about positioning of main subject, supporting elements, and background elements.
    - scene_description should include description about visual balance.
    - scene_description should include description about space allocation.
    - scene_description should include description about lighting, aiming for dynamic and engaging visuals.

visual_prompt: |
    Create a detailed, high-quality image for a video scene with the following specifications

    SCENE DESCRIPTION: {scene_description}
    SCRIPT: {script}
    IMAGE STYLE GUIDE: {image_style_guide}

    ESSENTIAL VISUAL ELEMENTS:
    - Must include: {image_keywords}
    - Image style guide: {image_style_guide}

    TECHNICAL SPECIFICATIONS:
    - Image ratio must be 9:16 (vertical format for mobile viewing)
    - High detail and clarity
    - Vibrant, attention-grabbing visuals
    - NO WATERMARKS OR LOGOS of any kind (YouTube, TikTok, etc.)

    COLOR AND COMPOSITION:
    - Follow the style guide for lighting and atmosphere
    - Use contrasting colors to highlight key elements
    - Ensure text readability with appropriate background contrast
    - Create visual hierarchy to guide viewer attention

    ADDITIONAL NOTES:
    This image will be animated with: {image_to_video}, Ensure the composition allows for this animation type.
    Create an image that is hooking, and make it more interesting with a surprising statement or question about a key scene element, like "What?! banana is radiation?" or "Human body can glow?!"
    Generate a single high-quality image in 9:16 aspect ratio that captures this scene perfectly for a video.

image_style_guide:
    "Scientific Illustration": "Precise, technical, clean line art with scientific accuracy, detailed cross-sections, blueprint-like precision, muted color palette, technical drawing style"
    "Cosmic Watercolor": "Dreamy watercolor technique, soft blended colors, astronomical elements, ethereal space-themed illustration, gentle color gradients, translucent textures"
    "Futuristic Digital Render": "Sleek, high-resolution 3D render, metallic and glass textures, minimalist design, sharp edges, cyberpunk-inspired color scheme, technological aesthetic"
    "Natural History Engraving": "Vintage scientific engraving style, intricate black and white detailed illustration, etched texture, 19th-century scientific journal aesthetic, precise linework"
    "Minimalist Infographic": "Clean, modern design, geometric shapes, flat color palette, iconographic representation, data visualization style, simple yet informative visual language"
    "Molecular Abstract": "Microscopic view, molecular and atomic structures, vibrant color palette, organic geometric shapes, translucent overlapping elements, scientific complexity visualized"
    "Retro Scientific Poster": "Vintage 1950s and 1960s scientific poster aesthetic, bold typography, mid-century modern color scheme, stylized graphic representations, nostalgic research illustration style"
    "Bioluminescent Fantasy": "Glowing, ethereal scientific imagery, neon-like colors, soft light effects, bio-inspired designs, dream-like interpretation of natural phenomena, luminescent textures"
    "Quantum Geometry": "Abstract mathematical representation, intricate geometric patterns, fractal-like designs, sharp angular shapes, cool color palette, representing complex scientific concepts"
    "Ecological Collage": "Layered natural elements, scientific diagram overlay, botanical and ecological details, mixed media approach, textured background, interconnected scientific ecosystem visualization"
