# Tech News Creator Configuration
youtube_channel_id: "YOUR_TECH_NEWS_CHANNEL_ID"
google_sheet_name: "tech_news"
content_prompt: |
    Create an engaging and informative short video about the latest technology news.

    The video should focus on: {detail}
    
    Guidelines:
    - Final video should be around 50~65 seconds
    - Present the information in a clear and engaging way
    - Use simple language to explain complex tech concepts
    - Include interesting visual elements that help explain the technology
    - Make the content memorable and shareable
    - End with a thought-provoking question or call to action
    - Target audience 15~35 years old tech enthusiasts
    - Make a hook more interesting with a surprising tech fact or innovation
    
    Target Audience: Tech enthusiasts, early adopters, and people interested in technology
    Core Principle: Make complex tech news accessible and exciting
    Tone: Professional yet approachable, enthusiastic about technology
    Goal: Transform tech news into engaging, easy-to-understand content
    Structure: Hook with latest innovation, context, impact, future implications
    Engagement: Real-world examples, visual demonstrations, analogies
    Impact: Help viewers understand and get excited about tech developments
    Ethics: Balanced reporting, fact-checking, source attribution
    Success Metrics: Engagement, comprehension, viewer retention
    Ultimate Aim: Bridge the gap between complex tech news and general audience

    LIST OF IMAGE STYLES NAMES: {image_style_list}

    FORMAT YOUR RESPONSE USING THE FOLLOWING JSON STRUCTURE:

    {
        "video_title": "Title of the video (Catchy and intriguing, emoji included)",
        "video_description": "Brief description of the video content, highlighting the tech innovation",
        "hashtags": ["hashtag1", "hashtag2", "hashtag3"],
        "hook": {
            "script": "Narration text for the hook, designed to grab attention with a tech fact",
            "image_keywords": ["keyword1", "keyword2", "visually striking tech elements"],
            "scene_description": "Detailed visual description including tech elements, UI/UX, devices, etc.",
            "image_to_video": "Description of how the static image should be animated",
            "image_style_name": "Style from the list above that best fits tech content"
        }
    } 